# Generated by Django 2.1.5 on 2019-01-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
